def menu():
    print("="*50)
    print("\t\tStudent Information System")
    print("="*50)
    print("\t\t1. Insert Student Data.")
    print("\t\t2. View Student Data Using Roll Number.")
    print("\t\t3. View All Student Data.")
    print("\t\t4. Search Student Data.")
    print("\t\t5. Delete Student Data.")
    print("\t\t6. Exit")
    print("="*50)
